name: Run Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy source code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài Java (ví dụ JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Bước 3: Cache thư viện Maven để build nhanh hơn
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Bước 4: Build và chạy test với Maven
      - name: Run Cucumber Tests
        run: mvn clean test

      # Bước 5 (Tuỳ chọn): Upload báo cáo Cucumber nếu có
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/