name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # manual trigger

jobs:
  test:
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Google Chrome
        run: |
          choco install googlechrome -y
          (Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion

      - name: Install ChromeDriver
        run: |
          $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          $chromeVersion = (Get-Item $chromePath).VersionInfo.FileVersion
          $chromeMajorVersion = $chrome
