name: Run Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Cucumber Tests
        run: mvn clean test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@8f733dbe3e91b0c6e60d8427a92c8fe593b6f6d0
        with:
          name: cucumber-report
          path: target/cucumber-reports/
